//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCPHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCPHAN()
        {
            this.DANGKies = new HashSet<DANGKY>();
        }
    
        public int MaHP { get; set; }
        public string TenHP { get; set; }
        public Nullable<int> SoTC { get; set; }
        public Nullable<double> HSDiemThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKY> DANGKies { get; set; }
    }
}
